pipeline {
    agent any;

    stages {
        stage ("Testing"){
            steps{
                script {
                   sh "echo hello-frontend"
                }
            }
        }
    }


}